let managemoney = '/Home/managemoney';
import moment from 'moment'
/* selectType:'',      // 请求参数
    selectKey:'',   // 请求到的数据获取
    itemKey:'',         // 渲染字段
    itemName:'',        // 渲染字段 */
export default {
  publicComponent:{   
    reportName:"R19",
    title:'各分行理财产品日均保有量统计表',
    search:[
      {
        text:'选择查询日期格式:',
        type:2,
        defaultValue:'0',
        selectType:'DATE_TYPE',
        itemKey:'dateTypeCode',         // 渲染请求参数
        itemName:'dateTypeName',         // 渲染字段
        option:[
          {
            dateTypeCode:'0',
            dateTypeName:'日'
          }
        ]
      },
      {
        text:'起始日期:',
        selectType:'UPDATE_DATE_START',
        relationship:'UPDATE_DATE_END',
        dateCalendarType:'start',
        defaultValue:moment('2017-11-20', 'YYYY-MM-DD'),
        type:3,
      },
      {
        text:'终止日期:',
        selectType:'UPDATE_DATE_END',
        relationship:'UPDATE_DATE_START',
        defaultValue:moment('2017-11-25', 'YYYY-MM-DD'),
        type:3,
      },
      {
        text:'产品代码:',   
        requestType:'reProdCode',     // 请求参数
        selectType:'PROD_ID',      // 传给后端的字段
        selectKey:'prodCodeList',     // 请求到的数据获取
        itemKey:'prodCode',           // 渲染字段
        itemName:'prodCode',          // 渲染字段
        type:1,
        method:'get',
      },
      { 
        text:'省份:', 
        selectType:'PROVINCE_CODE',
        selectKey:'provinceList',
        itemKey:'organCode',   
        itemName:'organName', 
        disabled:true,          
        type:2,
      },
      {
        text:'地市:',
        selectType:'PREFECTURE_CODE',
        selectKey:'areaList',
        itemKey:'organCode',   
        itemName:'organName', 
        disabled:true,          
        type:2,
      },
      {
        text:'市县:',
        selectType:'CITY_CODE',
        selectKey:'cityList',
        itemKey:'organCode',   
        itemName:'organName', 
        disabled:true,           
        type:2,
      },
      {
        text:'网点:',
        selectType:'BRANCE_CODE',
        selectKey:'branchList',
        itemKey:'organCode',   
        itemName:'organName', 
        disabled:true,         
        type:2,
      },
      {
        text:'产品状态:',
        requestType:'prodStatus',       
        selectType:'PROD_STATUS',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',         
        type:2,
        method:'get',
      },
      {
        text:'产品品牌:',
        requestType:'reBrand',       
        selectType:'AM_PROD_BRAND_CODE',
        selectKey:'brandList',
        itemKey:'brandCode',
        itemName:'brandName',
        type:2,
        method:'get',
      },
      {
        text:'产品运作模式:',
        requestType:'reProdoperModel',       
        selectType:'AM_PROD_OPERATION_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'产品收益类型:',
        requestType:'reProfitType',       
        selectType:'AM_PROD_PROFIT_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'投资者类型:',
        requestType:'dCustomerType',       
        selectType:'dCustomerType',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'机构客户:',
        requestType:'reProper',       
        selectType:'reProper',
        disabled:true,
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'机构属性:',
        requestType:'reOrganType',       
        selectType:'ORGAN_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'数据粒度:',
        requestType:'dSjld',       
        selectType:'ORGAN_LEVEL',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'发行币种:',
        requestType:'regCurrency',       
        selectType:'AM_PROD_CURRENCY',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      }
    ],
    tableResult:{
      columns:[
        {
          title:'机构代码',
          dataIndex:'ORGAN_ID',
          key:'ORGAN_ID'
        },
        {
          title:'机构名称',
          dataIndex:'ORGAN_NAME',
          key:'ORGAN_NAME'
        },
        {
          title:'日均保有量(万份)',
          dataIndex:'QUOTA',
          key:'QUOTA'
        }
      ],
    }
  },
  productReport:{
    title:'各理财产品日均保有量统计表',
    search:[
      {
        text:'选择查询日期格式:',
        type:2,
        defaultValue:'0',
        selectType:'dateType',
        itemKey:'dateTypeCode',         // 渲染请求参数
        itemName:'dateTypeName',         // 渲染字段
        option:[
          {
            dateTypeCode:'0',
            dateTypeName:'日'
          },
        ]
      },
      {
        text:'起始日期:',
        selectType:'UPDATE_DATE_START',
        defaultValue:moment(),
        type:3,
      },
      {
        text:'终止日期:',
        selectType:'UPDATE_DATE_END',
        defaultValue:moment(),
        type:3,
      },
      {
        text:'产品代码:',   
        requestType:'reProdCode',     
        selectType:'PROD_ID',      
        selectKey:'prodCodeList',     
        itemKey:'prodCode',           
        itemName:'prodCode',          
        type:1,
        method:'get',
      },
      { 
        text:'省份:', 
        requestType:'province',       
        selectType:'PROVINCE_CODE',
        selectKey:'provinceList',
        itemKey:'provinceCode',           
        itemName:'provinceName',         
        linkage:'areaCode',
        method:'get',
        type:2,
      },
      {
        text:'地市:',
        selectType:'PREFECTURE_CODE',
        selectKey:'areaList',
        itemKey:'areaCode',
        itemName:'areaName',         
        linkage:'cityCode',
        type:2,
      },
      {
        text:'市县:',
        selectType:'CITY_CODE',
        selectKey:'cityList',
        itemKey:'cityCode',
        itemName:'cityName',         
        linkage:'branchCode',
        type:2,
      },
      {
        text:'网点:',
        selectType:'BRANCE_CODE',
        selectKey:'branchList',
        itemKey:'branchCode',
        itemName:'branchName',         
        type:2,
      },
      {
        text:'产品状态:',
        requestType:'prodStatus',       
        selectType:'PROD_STATUS',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',         
        type:2,
        method:'get',
      },
      {
        text:'产品品牌:',
        requestType:'reBrand',       
        selectType:'AM_PROD_BRAND_CODE',
        selectKey:'brandList',
        itemKey:'brandCode',
        itemName:'brandName',
        type:2,
        method:'get',
      },
      {
        text:'产品运作模式:',
        requestType:'reProdoperModel',       
        selectType:'AM_PROD_OPERATION_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'产品收益类型:',
        requestType:'reProfitType',       
        selectType:'AM_PROD_PROFIT_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'投资者类型:',
        requestType:'dCustomerType',       
        selectType:'dCustomerType',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'机构客户:',
        requestType:'reProper',       
        selectType:'reProper',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'机构属性:',
        requestType:'reOrganType',       
        selectType:'ORGAN_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'发行币种:',
        requestType:'regCurrency',       
        selectType:'AM_PROD_CURRENCY',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      }
    ],
    tableResult:{
      columns:[
        {
          title:'产品代码',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'产品名称',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'日均保有量(万份)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        }
      ],
    }
  },
  information:{
    title:'理财产品基本信息表',
    search:[
      {
        text:'募集起始开始日期:',
        dateCalendarType:'start',
        selectType:'raising_start_day_start',
        relationship:'raising_start_day_end',
        type:3
      },
      {
        text:'募集起始结束日期:',
        selectType:'raising_start_day_end',
        relationship:'raising_start_day_start',
        type:3
      },
      {
        text:'募集终止开始日期:',
        dateCalendarType:'start',
        selectType:'raising_end_day_start',
        relationship:'raising_end_day_end',
        type:3
      },
      {
        text:'募集终止结束日期:',
        selectType:'raising_end_day_end',
        relationship:'raising_end_day_start',
        type:3
      },
      {
        text:'产品成立开始日期:',
        dateCalendarType:'start',
        selectType:'prod_found_date_start',
        relationship:'prod_found_date_end',
        type:3
      },
      {
        text:'产品成立结束日期:',
        selectType:'prod_found_date_end',
        relationship:'prod_found_date_start',
        type:3
      },
      {
        text:'产品终止开始日期:',
        dateCalendarType:'start',
        selectType:'prod_expire_date_start',
        relationship:'prod_expire_date_end',
        type:3
      },
      {
        text:'产品终止结束日期:',
        selectType:'prod_expire_date_end',
        relationship:'prod_expire_date_start',
        type:3
      },
      {
        text:'产品代码:',   
        requestType:'reProdCode',     
        selectType:'PROD_ID',      
        selectKey:'prodCodeList',     
        itemKey:'prodCode',           
        itemName:'prodCode',          
        type:1,
        method:'get',
      },
      {
        text:'产品名称:',
        selectType:'',
        selectKey:'',   
        itemKey:'',         
        itemName:'', 
        type:1,
        method:'get',
      },
      {
        text:'产品品牌:',
        requestType:'reBrand',       
        selectType:'AM_PROD_BRAND_CODE',
        selectKey:'brandList',
        itemKey:'brandCode',
        itemName:'brandName',
        type:2,
        method:'get',
      },
      {
        text:'产品研发人:',
        selectType:'',
        selectKey:'',
        itemKey:'',
        type:2
      },
      {
        text:'产品销售渠道:',
        requestType:'dChnl',
        selectType:'CHANNEL',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'产品收益类型:',
        requestType:'reProfitType',       
        selectType:'AM_PROD_PROFIT_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'机构客户:',
        requestType:'reProper',       
        selectType:'reProper',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'投资者类型:',
        requestType:'dCustomerType',       
        selectType:'dCustomerType',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'是否自主平衡:',
        selectType:'reAutoBalance',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'拟续接:',
        selectType:'reIsCont',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'待续接:',
        selectType:'',
        selectKey:'',
        itemKey:'',
        type:2,
        method:'get',
      },
      {
        text:'项目名称:',        
        selectType:'',
        selectKey:'',
        itemKey:'',
        type:2,
        method:'get',
      },
      {
        text:'项目研发人:',
        selectType:'',
        selectKey:'',
        itemKey:'',
        type:2,
        method:'get',
      },
      {
        text:'产品销售区域:',
        selectType:'',
        selectKey:'',
        itemKey:'',
        type:2,
        method:'get',
      },
      {
        text:'机构属性:',
        requestType:'reOrganType',       
        selectType:'ORGAN_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'发行币种:',
        requestType:'regCurrency',       
        selectType:'AM_PROD_CURRENCY',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      }
    ],
    tableResult:{
      columns:[
        {
          title:'序号',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'产品代码',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'产品名称:',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'发行币种:',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'产品品牌:',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'产品运作模式',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'产品收益类型:',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'募集起始日期:',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'募集结束日期',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'产品成立日期:',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'产品终止日期:',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'期限(天)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'计划募集规模(万元)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'实际募集规模(万元)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'',
          dataIndex:'companyAddress',
          key:'companyAddress'
        }
      ],
    }
  },
  closeStatistics:{
    title:'封闭式非净值型理财产品平均客户收益率及投资收益率统计表',
    search:[
      {
        text:'查询起始日期:',
        selectType:'UPDATE_DATE_START',
        defaultValue:moment(),
        type:3,
      },
      {
        text:'查询终止日期:',
        selectType:'UPDATE_DATE_END',
        defaultValue:moment(),
        type:3,
      },
      {
        text:'产品研发人',
        type:2,
        selectType:'',
        selectKey:'',
        itemKey:'',
        itenName:'',
        method:'get',
      },
      {
        text:'产品销售渠道:',
        requestType:'dChnl',
        selectType:'CHANNEL',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'产品收益类型:',
        requestType:'reProfitType',       
        selectType:'AM_PROD_PROFIT_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'机构客户:',
        requestType:'reProper',       
        selectType:'reProper',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'投资者类型:',
        requestType:'dCustomerType',       
        selectType:'dCustomerType',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'是否自主平衡:',
        selectType:'reAutoBalance',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'产品销售区域:',
        selectType:'',
        selectKey:'',
        itemKey:'',
        type:2,
        method:'get',
      },
      {
        text:'产品品牌:',
        requestType:'reBrand',       
        selectType:'AM_PROD_BRAND_CODE',
        selectKey:'brandList',
        itemKey:'brandCode',
        itemName:'brandName',
        type:2,
        method:'get',
      },
      {
        text:'项目研发人:',
        selectType:'',
        selectKey:'',
        type:1,
        method:'get',
      },
      {
        text:'发行币种:',
        selectType:'regCurrency',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      }
    ],
    tableResult:{
      columns:[
        {
          title:'',
          children:[
            {
              title: '序号',
              dataIndex: 'companyAddress',
              key: 'companyAddress', 
            }
          ]
        },
        {
          title:'',
          children:[
            {
              title:'产品期限分类',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
        {
          title:'全部存续产品',
          children:[
            {
              title:'客户收益率区间',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'平均客户收益率',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'投资收益率区间',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'平均投资收益率',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ],
        },
        {
          title:'查询期间新增产品',
          children:[
            {
              title:'客户收益率区间',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'平均客户收益率',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'投资收益率区间',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'平均投资收益率',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        }
      ],
    }
  },
  closedSequence:{
    title:'封闭式非净值型理财产品平均客户收益率及投资收益率序列表',
    search:[ 
      {
        text:'选择查询日期格式:',
        type:2,
        defaultValue:'0',
        isMonth:true,
        selectType:'dateType',
        itemKey:'dateTypeCode',          // 渲染请求参数
        itemName:'dateTypeName',         // 渲染字段
        option:[
          {
            dateTypeCode:'0',
            dateTypeName:'日'
          },
          {
            dateTypeCode:'1',
            dateTypeName:'月'
          },
        ]
      },
      {
        text:'起始日期:',
        selectType:'UPDATE_DATE_START',
        defaultValue:moment(),
        type:3,
      },
      {
        text:'终止日期:',
        selectType:'UPDATE_DATE_END',
        defaultValue:moment(),
        type:3,
      },
      {
        text:'产品研发人:',
        selectType:'',
        selectKey:'',
        itemKey:'',
        itemName:'',
        type:2,
        method:'get',
      },
      {
        text:'产品销售渠道:',
        requestType:'dChnl',
        selectType:'CHANNEL',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'产品收益类型:',
        requestType:'reProfitType',       
        selectType:'AM_PROD_PROFIT_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'机构客户类型:',
        requestType:'reProper',       
        selectType:'reProper',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'投资者类型:',
        requestType:'dCustomerType',       
        selectType:'dCustomerType',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'是否自主平衡:',
        selectType:'reAutoBalance',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'产品销售区域:',
        selectType:'',
        selectKey:'',
        itemKey:'',
        itemName:'',
        type:2,
        method:'get',
      },
      {
        text:'项目研发人:',
        selectType:'',
        selectKey:'',
        itemKey:'',
        itemName:'',
        type:2,
        method:'get',
      },
      {
        text:'产品品牌:',
        requestType:'reBrand',       
        selectType:'AM_PROD_BRAND_CODE',
        selectKey:'brandList',
        itemKey:'brandCode',
        itemName:'brandName',
        type:2,
        method:'get',
      },
      {
        text:'发行币种:',
        requestType:'regCurrency',       
        selectType:'AM_PROD_CURRENCY',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      }
    ],
    tableResult:{
      columns:[
        {
          title:'',
          children:[
            {
              title:'时间',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
        {
          title:'全部存续产品',
          children:[
            {
              title:'发行币种',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'客户收益率区间',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'平均客户收益率',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'投资收益率区间',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'平均投资收益率',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
        {
          title:'查询期间新增产品',
          children:[
            {
              title:'客户收益率区间',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'平均客户收益率',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'投资收益率区间',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'平均投资收益率',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        }
      ],
      dataSource:[
        {
            
        }
      ] 
    }
  },
  effectiveSales:{
    title:'理财产品有效销量表',
    search:[
      { 
        text:'省份:', 
        requestType:'province',       
        selectType:'PROVINCE_CODE',
        selectKey:'provinceList',
        itemKey:'provinceCode',           
        itemName:'provinceName',         
        linkage:'areaCode',
        method:'get',
        type:2,
      },
      {
        text:'地市:',
        selectType:'PREFECTURE_CODE',
        selectKey:'areaList',
        itemKey:'areaCode',
        itemName:'areaName',         
        linkage:'cityCode',
        type:2,
      },
      {
        text:'市县:',
        selectType:'CITY_CODE',
        selectKey:'cityList',
        itemKey:'cityCode',
        itemName:'cityName',         
        linkage:'branchCode',
        type:2,
      },
      {
        text:'网点:',
        selectType:'BRANCE_CODE',
        selectKey:'branchList',
        itemKey:'branchCode',
        itemName:'branchName',         
        type:2,
      },
      {
        text:'起始月份:',
        selectType:'UPDATE_DATE',
        dateFormat:'YYYY-MM',
        type:3,
      },
      {
        text:'结束月份:',
        selectType:'ENDDATE_DATE',
        dateFormat:'YYYY-MM',
        type:3,
      },
      {
        text:'数据粒度:',
        requestType:'dSjld',       
        selectType:'ORGAN_LEVEL',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'机构属性:',
        requestType:'reOrganType',       
        selectType:'ORGAN_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'发行币种:',
        requestType:'regCurrency',       
        selectType:'AM_PROD_CURRENCY',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      }
    ],
    tableResult:{
      columns:[
        {
          title:'机构代码',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'发行币种',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'机构名称',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'开放式产品日均保有量(个人)增量(万份)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'开放式产品日均保有量(个人)增量排名',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'开放式产品日均保有量(机构)增量(万份)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'开放式产品日均保有量(机构)增量排名',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'开放式日均保有量(合计)增量(万份)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'开放式产品日均保有量(合计)增量排名',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'封闭式产品销量(个人)(万元)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'封闭式产品销量(个人)排名',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'封闭式产品销量(机构)(万元)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'封闭式产品销量(机构)排名',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'封闭式产品销量(合计)(万元)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'封闭式产品销量(合计)排名',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'有效销量(个人)(万元)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'有效销量(个人)排名',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'有效销量(机构)(万元)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'有效销量(机构)排名',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'有效销量(合计)(万元)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'有效销量(合计)排名',
          dataIndex:'companyAddress',
          key:'companyAddress'
        }
      ],
    }
  },
  scaleSequence:{
    title:'理财产品供给规模与销售规模序列表',
    search:[
      {
        text:'起始月份:',
        selectType:'UPDATE_DATE',
        dateFormat:'YYYY-MM',
        type:3,
      },
      {
        text:'结束月份:',
        selectType:'ENDDATE_DATE',
        dateFormat:'YYYY-MM',
        type:3,
      },
      {
        text:'产品运作模式:',
        requestType:'reProdoperModel',       
        selectType:'AM_PROD_OPERATION_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'发行币种:',
        requestType:'regCurrency',       
        selectType:'AM_PROD_CURRENCY',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      }
    ],
    tableResult:{
      columns:[
        {
          title:'月份',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'发行币种',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'计划发售(万元)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'实际发送(万元)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'差额(万元)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'销售率',
          dataIndex:'companyAddress',
          key:'companyAddress'
        }
      ],
    }
  },
  customerSales:{
    title:'机构理财产品客户销售情况表',
    search:[
      {
        text:'起始日期:',
        selectType:'UPDATE_DATE_START',
        defaultValue:moment(),
        type:3,
      },
      {
        text:'终止日期:',
        selectType:'UPDATE_DATE_END',
        defaultValue:moment(),
        type:3,
      },
      {
        text:'产品代码:',   
        requestType:'reProdCode',     
        selectType:'PROD_ID',      
        selectKey:'prodCodeList',    
        itemKey:'prodCode',           
        itemName:'prodCode',          
        type:1,
        method:'get',
      },
      {
        text:'发行币种:',
        requestType:'regCurrency',       
        selectType:'AM_PROD_CURRENCY',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      }
    ],
    tableResult:{
      columns:[
        {
          title:'购买时间',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'发行币种',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'产品代码',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'产品名称',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'客户开户号',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'客户名称',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'认购金额(万元)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        }
      ],
    }
  },
  saleStatuSequence:{
    title:'理财销售情况序列表',
    search:[
      { 
        text:'省份:', 
        requestType:'province',       
        selectType:'PROVINCE_CODE',
        selectKey:'provinceList',
        itemKey:'provinceCode',           
        itemName:'provinceName',         
        linkage:'areaCode',
        method:'get',
        type:2,
      },
      {
        text:'地市:',
        selectType:'PREFECTURE_CODE',
        selectKey:'areaList',
        itemKey:'areaCode',
        itemName:'areaName',         
        linkage:'cityCode',
        type:2,
      },
      {
        text:'市县:',
        selectType:'CITY_CODE',
        selectKey:'cityList',
        itemKey:'cityCode',
        itemName:'cityName',         
        linkage:'branchCode',
        type:2,
      },
      {
        text:'网点:',
        selectType:'BRANCE_CODE',
        selectKey:'branchList',
        itemKey:'branchCode',
        itemName:'branchName',         
        type:2,
      },
      {
        text:'选择查询日期格式:',
        type:2,
        defaultValue:'0',
        isMonth:true,
        selectType:'dateType',
        itemKey:'dateTypeCode',         // 渲染请求参数
        itemName:'dateTypeName',         // 渲染字段
        option:[
          {
            dateTypeCode:'0',
            dateTypeName:'日'
          },
          {
            dateTypeCode:'1',
            dateTypeName:'月'
          },
        ]
      },
      {
        text:'起始日期:',
        selectType:'UPDATE_DATE_START',
        defaultValue:moment(),
        type:3,
      },
      {
        text:'终止日期:',
        selectType:'UPDATE_DATE_END',
        defaultValue:moment(),
        type:3,
      },
      {
        text:'投资者类型:',
        requestType:'dCustomerType',       
        selectType:'dCustomerType',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'机构客户:',
        requestType:'reProper',       
        selectType:'reProper',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'机构属性:',
        requestType:'reOrganType',       
        selectType:'ORGAN_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'产品运作模式:',
        requestType:'reProdoperModel',       
        selectType:'AM_PROD_OPERATION_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'产品收益类型:',
        requestType:'reProfitType',       
        selectType:'AM_PROD_PROFIT_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'产品销售渠道:',
        requestType:'dChnl',
        selectType:'CHANNEL',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'发行币种:',
        requestType:'regCurrency',       
        selectType:'AM_PROD_CURRENCY',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      }
    ],
    tableResult:{
      columns:[
        {
          title:'查询日期',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'发行币种',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'销量金额(万元)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'同比',
          dataIndex:'companyAddress',
          key:'companyAddress'
        }   
      ],
    }
  },
  closeSalesEnquiries:{
    title:'在售封闭式理财产品销售情况查询表',
    search:[
      {
        text:'查询日期:',
        selectType:'beginDate',
        type:3,
      },
      {
        text:'产品运作模式:',
        requestType:'reProdoperModel',       
        selectType:'AM_PROD_OPERATION_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'销售机构:',
        selectType:'reOrganType',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'发行币种:',
        requestType:'regCurrency',       
        selectType:'AM_PROD_CURRENCY',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      }
  ],
    tableResult:{
      columns:[
        {
          title:'产品名称',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'发行币种',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'计划发售(万元)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'实际发售(万元)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'差额(万元)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'销售率',
          dataIndex:'companyAddress',
          key:'companyAddress'
        }
      ],
    }
  },
  openSalesEnquiries:{
    title:'开放式理财产品销售情况查询表',
    search:[
      { 
        text:'省份:', 
        requestType:'province',       
        selectType:'PROVINCE_CODE',
        selectKey:'provinceList',
        itemKey:'provinceCode',           
        itemName:'provinceName',         
        linkage:'areaCode',
        method:'get',
        type:2,
      },
      {
        text:'地市:',
        selectType:'PREFECTURE_CODE',
        selectKey:'areaList',
        itemKey:'areaCode',
        itemName:'areaName',         
        linkage:'cityCode',
        type:2,
      },
      {
        text:'市县:',
        selectType:'CITY_CODE',
        selectKey:'cityList',
        itemKey:'cityCode',
        itemName:'cityName',         
        linkage:'branchCode',
        type:2,
      },
      {
        text:'网点:',
        selectType:'BRANCE_CODE',
        selectKey:'branchList',
        itemKey:'branchCode',
        itemName:'branchName',         
        type:2,
      },
      {
        text:'起始日期:',
        selectType:'UPDATE_DATE_START',
        defaultValue:moment(),
        type:3,
      },
      {
        text:'终止日期:',
        selectType:'UPDATE_DATE_END',
        defaultValue:moment(),
        type:3,
      },
      {
        text:'机构属性:',
        requestType:'reOrganType',       
        selectType:'ORGAN_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'产品运作模式:',
        requestType:'reProdoperModel',       
        selectType:'AM_PROD_OPERATION_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
    ],
    tableResult:{
      columns:[
        {
          title:'产品代码',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'产品名称',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'销售金额(个人)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'销售金额(机构)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'销售总金额(合计)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'销售份额(个人)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'销售份额(机构)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'销售总份额(合计)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'赎回金额(个人)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'赎回金额(机构)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'赎回总金额(合计)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'赎回份额(个人)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'赎回份额(机构)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'赎回总份额(合计)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'净增金额(个人)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'净增份额(个人)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'净增金额(机构)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'净增份额(机构)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'净增总金额(合计)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'净增总份数(合计)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        }
      ],
    }
  },
  openSaleSequence:{
    title:'开放式产品销售情况序列表',
    search:[
      { 
        text:'省份:', 
        requestType:'province',       
        selectType:'PROVINCE_CODE',
        selectKey:'provinceList',
        itemKey:'provinceCode',           
        itemName:'provinceName',         
        linkage:'areaCode',
        method:'get',
        type:2,
      },
      {
        text:'地市:',
        selectType:'PREFECTURE_CODE',
        selectKey:'areaList',
        itemKey:'areaCode',
        itemName:'areaName',         
        linkage:'cityCode',
        type:2,
      },
      {
        text:'市县:',
        selectType:'CITY_CODE',
        selectKey:'cityList',
        itemKey:'cityCode',
        itemName:'cityName',         
        linkage:'branchCode',
        type:2,
      },
      {
        text:'网点:',
        selectType:'BRANCE_CODE',
        selectKey:'branchList',
        itemKey:'branchCode',
        itemName:'branchName',         
        type:2,
      },
      {
        text:'选择查询日期格式:',
        type:2,
        defaultValue:'0',
        selectType:'dateType',
        itemKey:'dateTypeCode',         // 渲染请求参数
        itemName:'dateTypeName',         // 渲染字段
        option:[
          {
            dateTypeCode:'0',
            dateTypeName:'日'
          },
          {
            dateTypeCode:'1',
            dateTypeName:'月'
          },
        ]
      },
      {
        text:'起始日期:',
        selectType:'UPDATE_DATE_START',
        defaultValue:moment(),
        type:3,
      },
      {
        text:'终止日期:',
        selectType:'UPDATE_DATE_END',
        defaultValue:moment(),
        type:3,
      },
      {
        text:'产品代码:',   
        requestType:'reProdCode',     
        selectType:'PROD_ID',      
        selectKey:'prodCodeList',    
        itemKey:'prodCode',           
        itemName:'prodCode',          
        type:1,
        method:'get',
      },
      {
        text:'产品运作模式:',
        requestType:'reProdoperModel',       
        selectType:'AM_PROD_OPERATION_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'机构属性:',
        requestType:'reOrganType',       
        selectType:'ORGAN_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
    ],
    tableResult:{
      columns:[
        {
          title:'日期',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'销售金额(个人)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'销售金额(机构)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'销售总金额(合计)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'销售份额(个人)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'销售份额(机构)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'销售总份额(合计)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'赎回金额(个人)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'赎回金额(机构)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'赎回总金额(合计)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'赎回份额(个人)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'赎回份额(机构)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'赎回总份额(合计)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'净增金额(个人)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'净增份额(个人)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'净增金额(机构)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'净增份额(机构)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'净增总金额(合计)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'净增总份额(合计)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'当前保有量份数(个人)',
          dataIndex:'companyAddress',
          key:'comapnyAddress'
        }
      ],
    }
  },
  branchSaleStatistics:{
    title:'各分行理财产品销售情况统计表',
    search:[
      { 
        text:'省份:', 
        requestType:'province',       
        selectType:'PROVINCE_CODE',
        selectKey:'provinceList',
        itemKey:'provinceCode',           
        itemName:'provinceName',         
        linkage:'areaCode',
        method:'get',
        type:2,
      },
      {
        text:'地市:',
        selectType:'PREFECTURE_CODE',
        selectKey:'areaList',
        itemKey:'areaCode',
        itemName:'areaName',         
        linkage:'cityCode',
        type:2,
      },
      {
        text:'市县:',
        selectType:'CITY_CODE',
        selectKey:'cityList',
        itemKey:'cityCode',
        itemName:'cityName',         
        linkage:'branchCode',
        type:2,
      },
      {
        text:'网点:',
        selectType:'BRANCE_CODE',
        selectKey:'branchList',
        itemKey:'branchCode',
        itemName:'branchName',         
        type:2,
      },
      {
        text:'数据粒度:',
        requestType:'dSjld',       
        selectType:'ORGAN_LEVEL',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'产品代码:',   
        requestType:'reProdCode',     // 请求参数
        selectType:'PROD_ID',      // 传给后端的字段
        selectKey:'prodCodeList',     // 请求到的数据获取
        itemKey:'prodCode',           // 渲染字段
        itemName:'prodCode',          // 渲染字段
        type:1,
        method:'get',
      },
      /* {
        text:'产品名称:',
        selectType:'',
        selectKey:'',
        itemKey:'',
        itemName:'',
        type:1,
        method:'get',
      }, */
      {
        text:'产品状态:',
        requestType:'prodStatus',       
        selectType:'PROD_STATUS',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',         
        type:2,
        method:'get',
      },
      {
        text:'投资者类型:',
        requestType:'dCustomerType',       
        selectType:'dCustomerType',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'机构客户:',
        requestType:'reProper',       
        selectType:'reProper',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'起始日期:',
        selectType:'UPDATE_DATE_START',
        defaultValue:moment(),
        type:3,
      },
      {
        text:'终止日期:',
        selectType:'UPDATE_DATE_END',
        defaultValue:moment(),
        type:3,
      },
      {
        text:'产品品牌:',
        requestType:'reBrand',       
        selectType:'AM_PROD_BRAND_CODE',
        selectKey:'brandList',
        itemKey:'brandCode',
        itemName:'brandName',
        type:2,
        method:'get',
      },
      {
        text:'产品运作模式:',
        requestType:'reProdoperModel',       
        selectType:'AM_PROD_OPERATION_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'产品销售渠道:',
        requestType:'dChnl',
        selectType:'CHANNEL',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'机构属性:',
        requestType:'reOrganType',       
        selectType:'ORGAN_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'发行币种:',
        requestType:'regCurrency',       
        selectType:'AM_PROD_CURRENCY',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      }
    ],
    tableResult:{
      columns:[
        {
          title:'',
          children:[
            {
              title:'机构代码',
              daatIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
        {
          title:'',
          children:[
            {
              title:'机构名称',
              daatIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },,
        {
          title:'',
          children:[
            {
              title:'发行币种',
              daatIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },,
        {
          title:'0-50000',
          children:[
            {
              title:'笔数',
              daatIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'客户数',
              daatIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'金额',
              daatIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
        {
          title:'50000-100000',
          children:[
            {
              title:'笔数',
              daatIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'客户数',
              daatIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'金额',
              daatIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
        {
          title:'100000-500000',
          children:[
            {
              title:'笔数',
              daatIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'客户数',
              daatIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'金额',
              daatIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
        {
          title:'500000-1000000',
          children:[
            {
              title:'笔数',
              daatIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'客户数',
              daatIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'金额',
              daatIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
        {
          title:'1000000以上',
          children:[
            {
              title:'笔数',
              daatIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'客户数',
              daatIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'金额',
              daatIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
        {
          title:'全部',
          children:[
            {
              title:'笔数',
              daatIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'客户数',
              daatIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'金额',
              daatIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
      ],
    }
  },
  productSaleStatistics:{
    title:'各理财产品销售情况统计表',
    search:[
      { 
        text:'省份:', 
        requestType:'province',       
        selectType:'PROVINCE_CODE',
        selectKey:'provinceList',
        itemKey:'provinceCode',           
        itemName:'provinceName',         
        linkage:'areaCode',
        method:'get',
        type:2,
      },
      {
        text:'地市:',
        selectType:'PREFECTURE_CODE',
        selectKey:'areaList',
        itemKey:'areaCode',
        itemName:'areaName',         
        linkage:'cityCode',
        type:2,
      },
      {
        text:'市县:',
        selectType:'CITY_CODE',
        selectKey:'cityList',
        itemKey:'cityCode',
        itemName:'cityName',         
        linkage:'branchCode',
        type:2,
      },
      {
        text:'网点:',
        selectType:'BRANCE_CODE',
        selectKey:'branchList',
        itemKey:'branchCode',
        itemName:'branchName',         
        type:2,
      },
      {
        text:'产品状态:',
        requestType:'prodStatus',       
        selectType:'PROD_STATUS',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',         
        type:2,
        method:'get',
      },
      {
        text:'机构属性:',
        requestType:'reOrganType',       
        selectType:'ORGAN_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'投资者类型:',
        requestType:'dCustomerType',       
        selectType:'dCustomerType',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'机构客户:',
        requestType:'reProper',       
        selectType:'reProper',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'起始日期:',
        selectType:'UPDATE_DATE_START',
        defaultValue:moment(),
        type:3,
      },
      {
        text:'终止日期:',
        selectType:'UPDATE_DATE_END',
        defaultValue:moment(),
        type:3,
      },
      {
        text:'产品代码:',   
        requestType:'reProdCode',     
        selectType:'PROD_ID',      
        selectKey:'prodCodeList',     
        itemKey:'prodCode',           
        itemName:'prodCode',          
        type:1,
        method:'get',
      },
      {
        text:'产品名称:',
        selectType:'',
        selectKey:'',
        type:1,
        
        method:'get',
      },
      {
        text:'产品销售渠道:',
        requestType:'dChnl',
        selectType:'CHANNEL',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'是否自主平衡:',
        selectType:'reAutoBalance',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'产品运作模式:',
        requestType:'reProdoperModel',       
        selectType:'AM_PROD_OPERATION_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'发行币种:',
        requestType:'regCurrency',       
        selectType:'AM_PROD_CURRENCY',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      }
    ],
    tableResult:{
      columns:[
        {
          title:'',
          children:[
            {
              title:'产品代码',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
        {
          title:'',
          children:[
            {
              title:'产品名称',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
        {
          title:'',
          children:[
            {
              title:'产品状态',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
        {
          title:'',
          children:[
            {
              title:'发行币种',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
        {
          title:'0-50000',
          children:[
            {
              title:'笔数',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'客户数',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'金额',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
        {
          title:'50000-100000',
          children:[
            {
              title:'笔数',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'客户数',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'金额',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
        {
          title:'100000-500000',
          children:[
            {
              title:'笔数',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'客户数',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'金额',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
        {
          title:'500000-1000000',
          children:[
            {
              title:'笔数',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'客户数',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'金额',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
        {
          title:'1000000以上',
          children:[
            {
              title:'笔数',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'客户数',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'金额',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
        {
          title:'全部',
          children:[
            {
              title:'笔数',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'客户数',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'金额',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        }
      ],
    }
  },
  customerProductTrading:{
    title:'机构理财客户产品交易情况表',
    search:[
      {
        text:'起始日期:',
        selectType:'UPDATE_DATE_START',
        defaultValue:moment(),
        type:3,
      },
      {
        text:'终止日期:',
        selectType:'UPDATE_DATE_END',
        defaultValue:moment(),
        type:3,
      },
      {
        text:'客户开户号码:',
        selectType:'',
        selectKey:'',
        type:1,
        method:'get',
      },
      {
        text:'发行币种:',
        requestType:'regCurrency',       
        selectType:'AM_PROD_CURRENCY',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      }
    ],
    tableResult:{
      columns:[
        {
          title:'日期',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'产品名称',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'产品代码',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'发行币种',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'认购金额',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'赎回金额',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'到期兑付金额',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'分红金额',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'保有金额(万份)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        }
      ],
    }
  },
  branchBalanceStatistics:{
    title:'各分行理财余额统计查询表',
    search:[
      {
        text:'查询月份:',
        selectType:'UPDATE_DATE',
        dateFormat:'YYYY-MM',
        type:3,
      },
      {
        text:'地区分类:',
        requestType:'reAreaType',       
        selectType:'GROUP_BY',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',         
        type:2,
        method:'get',
      },
      {
        text:'产品收益类型:',
        requestType:'reProfitType',       
        selectType:'AM_PROD_PROFIT_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'产品运作模式:',
        requestType:'reProdoperModel',       
        selectType:'AM_PROD_OPERATION_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'机构属性:',
        requestType:'reOrganType',       
        selectType:'ORGAN_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'发行币种:',
        requestType:'regCurrency',       
        selectType:'AM_PROD_CURRENCY',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      }
    ],
    tableResult:{
      columns:[
        {
          title:'机构代码',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'合计',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'排名',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'地区',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'排名',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'个人理财(万份)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'机构理财(万份)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'排名',
          dataIndex:'companyAddress',
          key:'companyAddress'
        }
      ],
    }
  },
  balanceChangeStatistics:{
    title:'各分行理财余额变动统计表',
    search:[
      {
        text:'起始日期:',
        selectType:'UPDATE_DATE_START',
        defaultValue:moment(),
        type:3,
      },
      {
        text:'终止日期:',
        selectType:'UPDATE_DATE_END',
        defaultValue:moment(),
        type:3,
      },
      {
        text:'销售机构:',
        selectType:'reOrganType',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'投资者类型:',
        requestType:'dCustomerType',       
        selectType:'dCustomerType',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'机构客户:',
        requestType:'reProper',       
        selectType:'reProper',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'是否自主平衡:',
        selectType:'reAutoBalance',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'地区分类:',
        selectType:'reAreaType',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'发行币种:',
        requestType:'regCurrency',       
        selectType:'AM_PROD_CURRENCY',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      }
    ],
    tableResult:{
      columns:[
        {
          title:'地区',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'起始日余额(万份)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'起始日余额排名',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'终止日余额(万份)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'终止日余额排名',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'排名变动量',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'增量(万份)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'增量排名',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'增幅',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'增幅排名',
          dataIndex:'companyAddress',
          key:'companyAddress'
        }
      ],
    }
  },
  productBalanceSequence:{
    title:'各理财产品余额序列表',
    search:[
      { 
        text:'省份:', 
        requestType:'province',       
        selectType:'PROVINCE_CODE',
        selectKey:'provinceList',
        itemKey:'provinceCode',           
        itemName:'provinceName',         
        linkage:'areaCode',
        method:'get',
        type:2,
      },
      {
        text:'地市:',
        selectType:'PREFECTURE_CODE',
        selectKey:'areaList',
        itemKey:'areaCode',
        itemName:'areaName',         
        linkage:'cityCode',
        type:2,
      },
      {
        text:'市县:',
        selectType:'CITY_CODE',
        selectKey:'cityList',
        itemKey:'cityCode',
        itemName:'cityName',         
        linkage:'branchCode',
        type:2,
      },
      {
        text:'网点:',
        selectType:'BRANCE_CODE',
        selectKey:'branchList',
        itemKey:'branchCode',
        itemName:'branchName',         
        type:2,
      },
      {
        text:'选择查询日期格式:',
        type:2,
        defaultValue:'0',
        selectType:'dateType',
        itemKey:'dateTypeCode',         // 渲染请求参数
        itemName:'dateTypeName',         // 渲染字段
        option:[
          {
            dateTypeCode:'0',
            dateTypeName:'日'
          },
          {
            dateTypeCode:'1',
            dateTypeName:'月'
          },
        ]
      },
      {
        text:'起始日期:',
        selectType:'UPDATE_DATE_START',
        defaultValue:moment(),
        type:3,
      },
      {
        text:'终止日期:',
        selectType:'UPDATE_DATE_END',
        defaultValue:moment(),
        type:3,
      },
      {
        text:'投资者类型:',
        requestType:'dCustomerType',       
        selectType:'dCustomerType',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'机构客户:',
        requestType:'reProper',       
        selectType:'reProper',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'机构属性:',
        requestType:'reOrganType',       
        selectType:'ORGAN_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'产品运作模式:',
        requestType:'reProdoperModel',       
        selectType:'AM_PROD_OPERATION_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'产品收益类型:',
        requestType:'reProfitType',       
        selectType:'AM_PROD_PROFIT_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'发行币种:',
        requestType:'regCurrency',       
        selectType:'AM_PROD_CURRENCY',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      }
    ],
    tableResult:{
      columns:[
        {
          title:'查询日期',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'保有量(万份)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'同比(%)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'环比(%)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        }
      ],
    }
  },
  branchBalanceEnquiry:{
    title:'各分行发行自主平衡产品情况查询',
    search:[
      {
        text:'查询月份:',
        selectType:'UPDATE_DATE',
        dateFormat:'YYYY-MM',
        type:3,
      },
      {
        text:'发行币种:',
        requestType:'regCurrency',       
        selectType:'AM_PROD_CURRENCY',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      }
    ],
    tableResult:{
      columns:[
        {
          title:'机构代码',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'分行',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'发行币种',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'产品支数',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'发行规模(万份)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        }
      ],
    }
  },
  productRevenueStatistics:{
    title:'各理财产品收入情况统计表',
    search:[
      { 
        text:'省份:', 
        requestType:'province',       
        selectType:'PROVINCE_CODE',
        selectKey:'provinceList',
        itemKey:'provinceCode',           
        itemName:'provinceName',         
        linkage:'areaCode',
        method:'get',
        type:2,
      },
      {
        text:'地市:',
        selectType:'PREFECTURE_CODE',
        selectKey:'areaList',
        itemKey:'areaCode',
        itemName:'areaName',         
        linkage:'cityCode',
        type:2,
      },
      {
        text:'市县:',
        selectType:'CITY_CODE',
        selectKey:'cityList',
        itemKey:'cityCode',
        itemName:'cityName',         
        linkage:'branchCode',
        type:2,
      },
      {
        text:'网点:',
        selectType:'BRANCE_CODE',
        selectKey:'branchList',
        itemKey:'branchCode',
        itemName:'branchName',         
        type:2,
      },
      {
        text:'起始月份:',
        selectType:'beginDate',
        type:3,
      },
      {
        text:'终止月份:',
        selectType:'endDate',
        type:3,
      },
      {
        text:'投资者类型:',
        requestType:'dCustomerType',       
        selectType:'dCustomerType',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'产品代码:',   
        requestType:'reProdCode',     
        selectType:'PROD_ID',      
        selectKey:'prodCodeList',     
        itemKey:'prodCode',           
        itemName:'prodCode',          
        type:1,
        method:'get',
      },
      {
        text:'产品状态:',
        requestType:'prodStatus',       
        selectType:'PROD_STATUS',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',         
        type:2,
        method:'get',
      },
      {
        text:'产品运作模式:',
        requestType:'reProdoperModel',       
        selectType:'AM_PROD_OPERATION_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'产品收益类型:',
        requestType:'reProfitType',       
        selectType:'AM_PROD_PROFIT_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'产品品牌:',
        requestType:'reBrand',       
        selectType:'AM_PROD_BRAND_CODE',
        selectKey:'brandList',
        itemKey:'brandCode',
        itemName:'brandName',
        type:2,
        method:'get',
      },
      {
        text:'机构属性:',
        requestType:'reOrganType',       
        selectType:'ORGAN_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'发行币种:',
        requestType:'regCurrency',       
        selectType:'AM_PROD_CURRENCY',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      }
    ],
    tableResult:{
      columns:[
        {
          title:'',
          children:[
            {
              title:'产品名称',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
        {
          title:'',
          children:[
            {
              title:'产品代码',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
        {
          title:'已分配手续费',
          children:[
            {
              title:'销售手续费(万元)',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'推荐费(万元)',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'激励手续费(万元)',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'合计(万元)',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
        {
          title:'计提手续费',
          children:[
            {
              title:'销售手续费(万元)',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'推荐费(万元)',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'激励手续费(万元)',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'合计(万元)',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        }
      ],
    }
  },
  branchRevenueStatistics:{
    title:'各分行理财收入统计表',
    search:[
      { 
        text:'省份:', 
        requestType:'province',       
        selectType:'PROVINCE_CODE',
        selectKey:'provinceList',
        itemKey:'provinceCode',           
        itemName:'provinceName',         
        linkage:'areaCode',
        method:'get',
        type:2,
      },
      {
        text:'地市:',
        selectType:'PREFECTURE_CODE',
        selectKey:'areaList',
        itemKey:'areaCode',
        itemName:'areaName',         
        linkage:'cityCode',
        type:2,
      },
      {
        text:'市县:',
        selectType:'CITY_CODE',
        selectKey:'cityList',
        itemKey:'cityCode',
        itemName:'cityName',         
        linkage:'branchCode',
        type:2,
      },
      {
        text:'网点:',
        selectType:'BRANCE_CODE',
        selectKey:'branchList',
        itemKey:'branchCode',
        itemName:'branchName',         
        type:2,
      },
      {
        text:'起始月份:',
        selectType:'beginDate',
        type:3,
      },
      {
        text:'终止月份:',
        selectType:'endDate',
        type:3,
      },
      {
        text:'投资者类型:',
        requestType:'dCustomerType',       
        selectType:'dCustomerType',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'机构属性:',
        requestType:'reOrganType',       
        selectType:'ORGAN_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'产品代码:',   
        requestType:'reProdCode',     
        selectType:'PROD_ID',     
        selectKey:'prodCodeList',     
        itemKey:'prodCode',           
        itemName:'prodCode',          
        type:1,
        method:'get',
      },
      {
        text:'产品状态:',
        requestType:'prodStatus',       
        selectType:'PROD_STATUS',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',         
        type:2,
        method:'get',
      },
      {
        text:'产品运作模式:',
        requestType:'reProdoperModel',       
        selectType:'AM_PROD_OPERATION_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'产品收益类型:',
        requestType:'reProfitType',       
        selectType:'AM_PROD_PROFIT_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'产品品牌:',
        requestType:'reBrand',       
        selectType:'AM_PROD_BRAND_CODE',
        selectKey:'brandList',
        itemKey:'brandCode',
        itemName:'brandName',
        type:2,
        method:'get',
      },
      {
        text:'数据粒度:',
        requestType:'dSjld',       
        selectType:'ORGAN_LEVEL',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'发行币种:',
        requestType:'regCurrency',       
        selectType:'AM_PROD_CURRENCY',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      }
    ],
    tableResult:{
      columns:[
        {
          title:'',
          children:[
            {
              title:'机构代码',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
        {
          title:'',
          children:[
            {
              title:'机构名称',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
        {
          title:'已分配手续费',
          children:[
            {
              title:'销售手续费(万元)',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'推荐费(万元)',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'激励手续费(万元)',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'合计(万元)',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
        {
          title:'计提手续费',
          children:[
            {
              title:'销售手续费(万元)',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'推荐费(万元)',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'激励手续费(万元)',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'合计(万元)',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        }
      ],
    }
  },
  annualWithdrawing:{
    title:'年度销售手续费总计提/已分配/待分配确认表',
    search:[
      { 
        text:'省份:', 
        requestType:'province',       
        selectType:'PROVINCE_CODE',
        selectKey:'provinceList',
        itemKey:'provinceCode',           
        itemName:'provinceName',         
        linkage:'areaCode',
        method:'get',
        type:2,
      },
      {
        text:'地市:',
        selectType:'PREFECTURE_CODE',
        selectKey:'areaList',
        itemKey:'areaCode',
        itemName:'areaName',         
        linkage:'cityCode',
        type:2,
      },
      {
        text:'市县:',
        selectType:'CITY_CODE',
        selectKey:'cityList',
        itemKey:'cityCode',
        itemName:'cityName',         
        linkage:'branchCode',
        type:2,
      },
      {
        text:'网点:',
        selectType:'BRANCE_CODE',
        selectKey:'branchList',
        itemKey:'branchCode',
        itemName:'branchName',         
        type:2,
      },
      {
        text:'查询月份:',
        selectType:'UPDATE_DATE',
        dateFormat:'YYYY-MM',
        type:3,
      },
      {
        text:'投资者类型:',
        requestType:'dCustomerType',       
        selectType:'dCustomerType',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'机构属性:',
        requestType:'reOrganType',       
        selectType:'ORGAN_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'产品状态:',
        requestType:'prodStatus',       
        selectType:'PROD_STATUS',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',         
        type:2,
        method:'get',
      },
      {
        text:'产品代码:',   
        requestType:'reProdCode',     
        selectType:'PROD_ID',      
        selectKey:'prodCodeList',     
        itemKey:'prodCode',           
        itemName:'prodCode',          
        type:1,
        method:'get',
      },
      {
        text:'产品名称:',
        selectType:'',
        selectKey:'',
        type:1,
        method:'get',
      },
      {
        text:'发行币种:',
        requestType:'regCurrency',       
        selectType:'AM_PROD_CURRENCY',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      }
    ],
    tableResult:{
      columns:[
        {
          title:'产品代码',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'产品名称',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'当年计提手续费(万元)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'当年已分配金额(万元)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'历史已分配金额(万元)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'当年已分配次数',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'当年待分配金额(万元)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'年度跨期调整分配金额(万元)',
          dataIndex:'companyAddress',
          key:'companyAddress'
        }
      ],
    }
  },
  purchaseIntentionEnquiry:{
    title:'客户意向登记购买查询表',
    search:[
      {
        text:'起始日期:',
        selectType:'UPDATE_DATE_START',
        defaultValue:moment(),
        type:3,
      },
      {
        text:'终止日期:',
        selectType:'UPDATE_DATE_END',
        defaultValue:moment(),
        type:3,
      },
      {
        text:'地区:',
        selectType:'reAreaType',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'发行币种:',
        requestType:'regCurrency',       
        selectType:'AM_PROD_CURRENCY',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      }
    ],
    tableResult:{
      
    }
  },
  newCustomer:{
    title:'新增客户开户数',
    search:[
      {
        text:'起始日期:',
        selectType:'UPDATE_DATE_START',
        defaultValue:moment(),
        type:3,
      },
      {
        text:'终止日期:',
        selectType:'UPDATE_DATE_END',
        defaultValue:moment(),
        type:3,
      },
      {
        text:'投资者类型:',
        requestType:'dCustomerType',       
        selectType:'dCustomerType',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'机构客户:',
        requestType:'reProper',       
        selectType:'reProper',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
    ],
    tableResult:{
      columns:[
        {
          title:'机构代码',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'机构名称',
          dataIndex:'companyAddress',
          key:'companyAddress'
        },
        {
          title:'新增开户数',
          dataIndex:'companyAddress',
          key:'companyAddress'
        }
      ],
    }
  },
  branchComprehensiveStatistic:{
    title:'各分行理财产品综合情况统计表',
    search:[
      { 
        text:'省份:', 
        requestType:'province',       
        selectType:'PROVINCE_CODE',
        selectKey:'provinceList',
        itemKey:'provinceCode',           
        itemName:'provinceName',         
        linkage:'areaCode',
        method:'get',
        type:2,
      },
      {
        text:'地市:',
        selectType:'PREFECTURE_CODE',
        selectKey:'areaList',
        itemKey:'areaCode',
        itemName:'areaName',         
        linkage:'cityCode',
        type:2,
      },
      {
        text:'市县:',
        selectType:'CITY_CODE',
        selectKey:'cityList',
        itemKey:'cityCode',
        itemName:'cityName',         
        linkage:'branchCode',
        type:2,
      },
      {
        text:'网点:',
        selectType:'BRANCE_CODE',
        selectKey:'branchList',
        itemKey:'branchCode',
        itemName:'branchName',         
        type:2,
      },
      {
        text:'数据粒度:',
        requestType:'dSjld',       
        selectType:'ORGAN_LEVEL',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'起始日期:',
        selectType:'UPDATE_DATE_START',
        defaultValue:moment(),
        type:3,
      },
      {
        text:'终止日期:',
        selectType:'UPDATE_DATE_END',
        defaultValue:moment(),
        type:3,
      },
      {
        text:'投资者类型:',
        requestType:'dCustomerType',       
        selectType:'dCustomerType',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'机构客户:',
        requestType:'reProper',       
        selectType:'reProper',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'机构属性:',
        requestType:'reOrganType',       
        selectType:'ORGAN_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'产品品牌:',
        requestType:'reBrand',       
        selectType:'AM_PROD_BRAND_CODE',
        selectKey:'brandList',
        itemKey:'brandCode',
        itemName:'brandName',
        type:2,
        method:'get',
      },
      {
        text:'产品状态:',
        requestType:'prodStatus',       
        selectType:'PROD_STATUS',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',         
        type:2,
        method:'get',
      },
      {
        text:'产品运作模式:',
        requestType:'reProdoperModel',       
        selectType:'AM_PROD_OPERATION_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'产品收益类型:',
        requestType:'reProfitType',       
        selectType:'AM_PROD_PROFIT_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'产品销售渠道:',
        requestType:'dChnl',
        selectType:'CHANNEL',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'产品代码:',   
        requestType:'reProdCode',     
        selectType:'PROD_ID',     
        selectKey:'prodCodeList',     
        itemKey:'prodCode',           
        itemName:'prodCode',          
        type:1,
        method:'get',
      },
      {
        text:'产品名称:',
        selectType:'',
        selectKey:'',
        type:1,
        method:'get',
      },
      {
        text:'发行币种:',
        requestType:'regCurrency',       
        selectType:'AM_PROD_CURRENCY',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      }
    ],
    tableResult:{
      columns:[
        {
          title:'',
          children:[
            {
              title:'机构代码',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
        {
          title:'',
          children:[
            {
              title:'发行币种',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
        {
          title:'',
          children:[
            {
              title:'机构名称',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
        {
          title:'预约购买',
          children:[
            {
              title:'金额',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'份额(万份)',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'笔数',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'客户数',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
        {
          title:'购买',
          children:[
            {
              title:'金额',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'份额(万份)',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'笔数',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'客户数',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        }
      ],
    }
  },
  comprehensiveProductStatistics:{
    title:'各理财产品综合情况统计表',
    search:[
      { 
        text:'省份:', 
        requestType:'province',       
        selectType:'PROVINCE_CODE',
        selectKey:'provinceList',
        itemKey:'provinceCode',           
        itemName:'provinceName',         
        linkage:'areaCode',
        method:'get',
        type:2,
      },
      {
        text:'地市:',
        selectType:'PREFECTURE_CODE',
        selectKey:'areaList',
        itemKey:'areaCode',
        itemName:'areaName',         
        linkage:'cityCode',
        type:2,
      },
      {
        text:'市县:',
        selectType:'CITY_CODE',
        selectKey:'cityList',
        itemKey:'cityCode',
        itemName:'cityName',         
        linkage:'branchCode',
        type:2,
      },
      {
        text:'网点:',
        selectType:'BRANCE_CODE',
        selectKey:'branchList',
        itemKey:'branchCode',
        itemName:'branchName',         
        type:2,
      },
      {
        text:'起始日期:',
        selectType:'UPDATE_DATE_START',
        defaultValue:moment(),
        type:3,
      },
      {
        text:'终止日期:',
        selectType:'UPDATE_DATE_END',
        defaultValue:moment(),
        type:3,
      },
      {
        text:'机构客户:',
        requestType:'reProper',       
        selectType:'reProper',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'机构属性:',
        requestType:'reOrganType',       
        selectType:'ORGAN_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'产品品牌:',
        requestType:'reBrand',       
        selectType:'AM_PROD_BRAND_CODE',
        selectKey:'brandList',
        itemKey:'brandCode',
        itemName:'brandName',
        type:2,
        method:'get',
      },
      {
        text:'产品状态:',
        requestType:'prodStatus',       
        selectType:'PROD_STATUS',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',         
        type:2,
        method:'get',
      },
      {
        text:'产品运作模式:',
        requestType:'reProdoperModel',       
        selectType:'AM_PROD_OPERATION_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'产品收益类型:',
        requestType:'reProfitType',       
        selectType:'AM_PROD_PROFIT_MODE',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'产品销售渠道:',
        requestType:'dChnl',
        selectType:'CHANNEL',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      },
      {
        text:'产品代码:',   
        requestType:'reProdCode',     
        selectType:'PROD_ID',      
        selectKey:'prodCodeList',     
        itemKey:'prodCode',           
        itemName:'prodCode',          
        type:1,
        method:'get',
      },
      {
        text:'产品名称:',
        selectType:'',
        selectKey:'',
        type:1,
        method:'get',
      },
      {
        text:'发行币种:',
        requestType:'regCurrency',       
        selectType:'AM_PROD_CURRENCY',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      }
    ],
    tableResult:{
      columns:[
        {
          title:'',
          children:[
            {
              title:'产品代码',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
        {
          title:'',
          children:[
            {
              title:'发行币种',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
        {
          title:'',
          children:[
            {
              title:'产品名称',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
        {
          title:'预约购买',
          children:[
            {
              title:'金额',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'份额(万份)',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'笔数',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'客户数',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        },
        {
          title:'购买',
          children:[
            {
              title:'金额',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'份额(万份)',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'笔数',
              dataIndex:'companyAddress',
              key:'companyAddress'
            },
            {
              title:'客户数',
              dataIndex:'companyAddress',
              key:'companyAddress'
            }
          ]
        }
      ],
    }
  },
  weeklyQuery:{
    title:'周报数据查询表',
    search:[
      {
        text:'查询周期:',
        selectType:'reQueryWeek',
        type:3,
      },
      {
        text:'发行币种:',
        requestType:'regCurrency',       
        selectType:'AM_PROD_CURRENCY',
        selectKey:'list',
        itemKey:'value',
        itemName:'label',
        type:2,
        method:'get',
      }
    ],
    tableResult:{
      columns:[

      ],
    }
  }
}